apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../namespaces/trading-saas.yml
  - configmaps.yml
  - market-data-service.yml
  - trading-core-service.yml
  - ai-engine.yml
  - web-app.yml
  - hpa.yml
  - ingress.yml
  - network-policies.yml
