"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { Button } from "@/components/ui/button";
import {
  apiClient,
  type DeepAnalysisResponse,
  type DeepAnalysisSection,
} from "@/lib/api-client";

type DeepAnalysisCardProps = {
  signalId: string;
  isPremium: boolean;
};

const ROLE_LABELS: Record<DeepAnalysisSection["role"], string> = {
  BULL: "Bull case",
  BEAR: "Bear case",
  RISK: "Key risks",
  JUDGE: "Verdict",
};

function verdictTone(direction: DeepAnalysisResponse["verdictDirection"]): string {
  switch (direction) {
    case "BULLISH":
      return "text-green";
    case "BEARISH":
      return "text-red";
    default:
      return "text-amber-300";
  }
}

function convictionMeta(conviction: DeepAnalysisResponse["conviction"]): {
  label: string;
  className: string;
} {
  switch (conviction) {
    case "CONTRADICTS":
      return {
        label: "Low conviction — the debate verdict contradicts this signal.",
        className: "border-amber-400/40 bg-amber-400/[0.06] text-amber-200",
      };
    case "AGREES":
      return {
        label: "The debate verdict agrees with this signal.",
        className: "border-emerald-400/30 bg-emerald-400/[0.05] text-emerald-200",
      };
    default:
      return {
        label: "The debate verdict is neutral or inconclusive.",
        className: "border-border bg-bg-2 text-text-2",
      };
  }
}

function SectionBlock({ section }: { section: DeepAnalysisSection }) {
  const label = ROLE_LABELS[section.role] ?? section.role;
  return (
    <div className="rounded-2xl border border-border bg-bg-2 p-4">
      <div className="text-xs uppercase tracking-[0.22em] text-text-3">{label}</div>
      {section.refused ? (
        <p className="mt-2 text-sm italic leading-7 text-text-3">
          Withheld — this view did not pass the grounding check.
        </p>
      ) : (
        <p className="mt-2 text-sm leading-7 text-text-1">{section.text}</p>
      )}
    </div>
  );
}

function AnalysisView({ analysis }: { analysis: DeepAnalysisResponse }) {
  const conviction = convictionMeta(analysis.conviction);
  return (
    <div className="mt-6 space-y-4">
      <div className="flex items-center justify-between gap-4 rounded-2xl border border-border bg-bg-2 p-4">
        <div>
          <div className="text-xs uppercase tracking-[0.22em] text-text-3">Verdict</div>
          <div className={`mt-1 font-mono text-2xl font-bold ${verdictTone(analysis.verdictDirection)}`}>
            {analysis.verdictDirection}
          </div>
        </div>
        {analysis.outcome === "PARTIAL" ? (
          <span className="rounded-full border border-amber-400/30 px-3 py-1 text-[10px] uppercase tracking-[0.22em] text-amber-200">
            Partial
          </span>
        ) : null}
      </div>

      <div className={`rounded-2xl border p-4 text-sm leading-7 ${conviction.className}`}>
        {conviction.label}
      </div>

      {analysis.verdict ? <SectionBlock section={analysis.verdict} /> : null}
      {analysis.sections.map((section) => (
        <SectionBlock key={section.role} section={section} />
      ))}

      <p className="text-[11px] text-text-3">
        Analysis, not an order. Generated by {analysis.provider} · {analysis.modelVersion}.
      </p>
    </div>
  );
}

export function DeepAnalysisCard({ signalId, isPremium }: DeepAnalysisCardProps) {
  const queryClient = useQueryClient();

  const { data: analysis, isLoading } = useQuery({
    queryKey: ["deep-analysis", signalId],
    queryFn: () => apiClient.getDeepAnalysis(signalId),
    enabled: isPremium,
    staleTime: 5 * 60 * 1000,
  });

  const generate = useMutation({
    mutationFn: () => apiClient.generateDeepAnalysis(signalId),
    onSuccess: (result) => {
      queryClient.setQueryData(["deep-analysis", signalId], result);
    },
  });

  function renderContent() {
    if (!isPremium) {
      return (
        <p className="mt-6 text-sm leading-7 text-text-2">
          Deep analysis runs a grounded bull / bear / judge / risk debate over the signal.
          It is a <span className="text-cyan">Premium</span> feature — upgrade to unlock it.
        </p>
      );
    }

    if (isLoading) {
      return (
        <div className="mt-6 space-y-3">
          <div className="h-3 w-3/4 animate-pulse rounded-full bg-bg-2" />
          <div className="h-3 w-full animate-pulse rounded-full bg-bg-2" />
          <div className="h-3 w-2/3 animate-pulse rounded-full bg-bg-2" />
        </div>
      );
    }

    if (analysis) {
      return (
        <>
          <AnalysisView analysis={analysis} />
          <Button
            variant="outlineCyan"
            size="sm"
            className="mt-6"
            disabled={generate.isPending}
            onClick={() => generate.mutate()}
          >
            {generate.isPending ? "Regenerating…" : "Regenerate"}
          </Button>
        </>
      );
    }

    return (
      <div className="mt-6">
        <p className="text-sm leading-7 text-text-2">
          No deep analysis yet. Run the multi-agent debate to get an independent second opinion
          on this signal.
        </p>
        <Button
          variant="outlineCyan"
          size="sm"
          className="mt-4"
          disabled={generate.isPending}
          onClick={() => generate.mutate()}
        >
          {generate.isPending ? "Running debate…" : "Run deep analysis"}
        </Button>
        {generate.isError ? (
          <p className="mt-3 text-sm text-red">
            Deep analysis is temporarily unavailable. Please try again later.
          </p>
        ) : null}
      </div>
    );
  }

  return (
    <article className="rounded-[24px] border border-border bg-bg-1/80 p-6 shadow-glow">
      <div className="font-mono text-[11px] uppercase tracking-[0.22em] text-cyan">
        Deep analysis · Premium
      </div>
      <h3 className="mt-3 font-display text-2xl font-semibold tracking-[-0.04em] text-white">
        Multi-agent debate
      </h3>
      {renderContent()}
    </article>
  );
}
